
# server
server:
  port: 8081
  servlet:
    context-path: /bank/account


# Spring
spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:account
  session:
    store-type: jdbc
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #Swagger 3
# Environment
CUSTOMER: bank-customer

customer:
  api:
    url: http://localhost:8080/bank/customer

# Circuit Breaker
resilience4j.circuitbreaker:
  instances:
    backendA:
      registerHealthIndicator: true
      eventConsumerBufferSize: 10
      failureRateThreshold: 50
      minimumNumberOfCalls: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowSize: 10
      slidingWindowType: TIME_BASED
      slowCallDurationThreshold : 3000

#management:
#  health:
#    circuitbreakers:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: health
#  endpoint:
#    health:
#      show-details: always
